# configs/train.rf.yaml

runtime:
  seed: 42

rf_detr:
  epochs: 3
  batch_size: 2
  learning_rate: 0.0001
  backbone: dinov2_vits14
  patch_size: 14
  img_size: 728
  weights: rfdetr-m.pt
  max_train_samples: null
  max_valid_samples: null